### ISSUE TITLE
How can I initialize anchorProvider?

### ISSUE THREAD

**Issue by tolgaand** [heliofi/heliopay#27]
Hi guys, you did a great job, congratulations!

https://github.com/heliofi/heliopay#3-dynamic-payment-without-embedded-button

I'm trying to implement this step.

```javascript

  const onClickButton = async() => {
    if (!product) return;

      const signature = await sendTransaction(
        product.currency,
        {
          amount: product.normalizedPrice,
          sender: anchorProvider.provider.wallet.publicKey,
          recipient: new PublicKey("..."),
          mintAddress: new PublicKey("..."),
          cluster,
        },
        anchorProvider
      );
      
  };
```

But I have no idea how I should initialize `anchorProvider`, how can I import `anchorProvider`?
Sorry for this simple question, thanks very much!

**Comment by 00MB** [comment]
Message me on discord MichaelBeer#0001
